### ISSUE TITLE
I feel like I might be being a tad bitter, but...

### ISSUE THREAD

**Issue by shymega** [shymega/RSSingle#2]
Hey,

It's the maintainer and creator of `singlerss` here. I noted that your fork is just a clone of mine, with no forking history. Amongst the changes you've made, and adding `pyinstaller` support, which is really cool, I'd like it if you could contribute upstream to my legacy branch. 

I also noted that you're asking for donations, and I get a very small mention at the bottom of the README. Don't get me wrong, I love open source. It's such an open and transparent way of working. But asking for donations, with not too many changes to the base code, which I wrote myself, changing the name, and then not using the fork button to show the relationship between the two projects, makes me feel a bit dejected, or perhaps bitter.

I guess this is the nature of the open source, but it feels like my hard work has been taken and rebranded, without much attribution.

Do you think you could contribute upstream to the legacy branch, and add the forking relationship again? You can achieve that with GitHub support. I'm sure you can see where I'm coming from. It feels like I'm being a bit of an arse, but it really hurts to see my code without much attribution.

Thanks!

**Comment by tanrax** [comment]
Hello @shymega,

nice to greet you. You have done a great job. I'll respond to the points you leave me.

I don't intend to include my changes to your project because the approach I'm taking is different from yours, I'm going to go for running it on local machines. On the other hand I have not only included Pyinstaller, I have made the software more accessible by creating binaries for Linux and Windows (and automating the process with Docker), I have made the configuration easier by including a YAML avoiding environment variables and I have extended the README with the steps to use it. There are about 35 lines changed if we include formatting changes. Also, I think the name is more funny. On your side there are Pull Requests without working for several years, and it seems that you want to focus on AWS Lambda.

As you can see, I don't hide the origin of the software: I have kept your signature inside the code, I have referenced your GitHub username and the repository link. It's not just a small mention, I do all the honors to let it be known who was the developer who made the project possible.

I ask for donations in all my projects, blog and content I share. The goal is not to "sell your code", the goal is to receive support from the community to keep spending hours. I am currently struggling to create a binary on MacOS, whose work goes beyond the code itself.

I'm sorry if you feel hurt, but that's how Opensource works. Anyone can use your code, clone it, modify it and distribute it freely. That's the beauty of this world, it's what makes it possible that there are so many Linux distributions, projects available and software available to the community.

Honestly, it seems to me like a tantrum, an unserious request. It is not appropriate for an open source maintainer. Besides this message you should send it to me privately in an email, in my profile is visible my web and social networks.

I propose 2 solutions:

1. We work together: You leave your repository in read mode and continue from mine. You stop being a reference and become a collaborator at my level. We look for another means of donations.

2. You continue working on your repository: You create a fork from mine and rename it as you like or integrate it into yours.

I'm not looking to divide forces, I really like your code and I bet on it because I saw potential in it.

Best regards

**Comment by shymega** [comment]
> Hello @shymega,

Hey. I'm going to respond in-line. Sorry for the late reply. I wrote this issue on my way back from hols, and then I tested positive for COVID when I got home. I haven't been feeling myself. The good news is that I've had time to read through your response.

> nice to greet you. You have done a great job. I'll respond to the points you leave me.
> 
> I don't intend to include my changes to your project because the approach I'm taking is different from yours, I'm going to go for running it on local machines. On the other hand I have not only included Pyinstaller, I have made the software more accessible by creating binaries for Linux and Windows (and automating the process with Docker), I have made the configuration easier by including a YAML avoiding environment variables and I have extended the README with the steps to use it. There are about 35 lines changed if we include formatting changes. 

I did like the PyInstaller approach.

> Also, I think the name is more funny. On your side there are Pull Requests without working for several years, and it seems that you want to focus on AWS Lambda.

There was only one PR, and I left it open to wait for the author to respond, as it wasn't the best PR, and had a lot of mistakes. I wanted to educate the author, and help them with future PRs, but they didn't respond. You may have noticed it's been closed now.

> As you can see, I don't hide the origin of the software: I have kept your signature inside the code, I have referenced your GitHub username and the repository link. It's not just a small mention, I do all the honors to let it be known who was the developer who made the project possible.

Well, I was referring to the fork link - I was confused why you didn't fork from the repo, but instead created a new repo, and pushed it from my repo's history. Just seemed a bit odd. I would have personally done that, then renamed the fork. That way, you keep the better name (and for the record, singlerss was a terrible name, I'm really bad at naming things), and also show the origins. Just what I thought.

> I ask for donations in all my projects, blog and content I share. The goal is not to "sell your code", the goal is to receive support from the community to keep spending hours. I am currently struggling to create a binary on MacOS, whose work goes beyond the code itself.

Well, I'm sure you can see how I interpreted that. Now that you've explained, that makes sense. What issues are you having on macOS?

> I'm sorry if you feel hurt, but that's how Opensource works. Anyone can use your code, clone it, modify it and distribute it freely. That's the beauty of this world, it's what makes it possible that there are so many Linux distributions, projects available and software available to the community.

I totally understand that. I suppose, I just felt by cloning and pushing, without using the fork function, it seemed a bit 'off' to me. That is why I wrote the issue, and I didn't want to cause any upset.

> Honestly, it seems to me like a tantrum, an unserious request. It is not appropriate for an open source maintainer. Besides this message you should send it to me privately in an email, in my profile is visible my web and social networks.

It was not a tantrum. At the core of this issue, I wanted to understand the reasoning, and by opening an issue, I hoped to embrace transparency of open source, and by sending a private email - either of us could claim the other said something, and by acting publicly, we keep things transparent. I thought keeping it on a public repo would be suitable. I understand your objection, and I do apologise.

> 
> I propose 2 solutions:
> 
> 1. We work together: You leave your repository in read mode and continue from mine. You stop being a reference and become a collaborator at my level. We look for another means of donations.

I've been exploring your repo, and my approach with AWS Lambda, AWS DynamoDB, AWS S3 and AWS API Gateway is inferior. You made a good call in using GitHub Actions - definitely a good call. I am working on my repo and making it into a class-based approach, rather than just a single file of spaghetti code. I think, let's put this behind us - and work together. Do you use IRC or any other IM, such as Matrix or Telegram? I'm thinking a real-time discussion would work.

> 2. You continue working on your repository: You create a fork from mine and rename it as you like or integrate it into yours.
> 
> I'm not looking to divide forces, I really like your code and I bet on it because I saw potential in it.

Thank you, that's very kind.

**Comment by tanrax** [comment]
@shymega All right, I am leaving this issue public because I also believe in transparency. There has been no malicious intent on anyone's part, we have clarified several issues. We have clarified and we know each other's point of view, I think we can now work.
Do you have access to my email? I would like to talk to you about MacOS and distribution issues.

**Comment by tanrax** [comment]
I am closing it, although it will be possible to continue reading.

**Comment by shymega** [comment]
Sure, I will email you as soon as I have a chance.

**Comment by shymega** [comment]
Hey @tanrax, I just tried to email with the email you used in the repo's Git log, but I got a bounce. Can you send me an email? Thanks! :)
